name: Build and Deploy Story

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: python generate_story.py
    - uses: actions/upload-pages-artifact@v2
      with:
        path: ./output
    - uses: actions/deploy-pages@v2
